* -----------------------------------------------------------------------------
* NBM-Processing README - Data 
*
* michael byrne
* FEDERAL COMMUNICATIONS COMMISSION
*
* Created on: 5/24/2012
* 
* State Broadband Initiative
* NTIA / FCC
* -----------------------------------------------------------------------------

This repository contains the all the scripts used to initially process 
the National Broadband Map data submissions.

All submissions run on:
  
 * ESRI ArcInfo software
 * the NBM Data Transfer Data Model (file geodatabase)
 * in a standard directory structure with subfolders for each two letter state
     abbreviation.  It is assumed there is a file geodatabase of that state 
     in the state subfolder.  Each file geodatabase follows a normal naming convention
     including the state abbreviation and the month, day and year of the submission.

There are 4 phases in the submission:
Phase 1
  - the Check Submission which checks to see if the submission follows NBM business rules
  - this script has been updated (7/6/12) to include issues SBI awardees have raised and 
	  	NTIA has agreed to.  For a complete list of updated see the update notes in this 
  		directory.

Phase 2 
  - State Summary which creates the state summary file for each states submission
  - Business Rules which enforces NBM business rules, and cleans any data not conforming 
		to these rules
  - Append FRQ which generates an appended unique list of FRN, DBA, and ProvName fields
  - UniqueID which prepares and populates a unique ID Field

Phase 3
  - Data prep which performs the wireless block overlay, and the random point file 
  		generation
  - FRQFRN which generates a table of unique FRNs across the datasets
  - Export which exports all the data out of the file geodatabsse into a standard 
  		format to be read into a database (Postgres)

Phase 4
  - Spatial Layers which geoprocesses the data out of the file geodatabase and into 
  		common formats as shapefiles so it can be loaded into PostGres


Running the scripts
- After loading your data into the Data Transfer Model, add a tbx file to ArcCatalog.   
 	 We strongly suggest using ArcCatalog over ArcMap for a number of reasons.  

- With the .tbx file added to ArcToolbox, attach the associated script and run it.

- You will need to check this script for any 'FAILED' printed results.  A FAILED result 
	means there are unexpected values in your data submission.  You will need to locate 
	the values, fix the issues and  rerun the tool.

- We would like you to submit the reciept file (the .txt file generated by the tool)
	 with your submission.

NOTES:
- PLEASE NOTE: THIS TOOL RUNS THE ESRI CHECK AND REPAIR GEOMETRY TOOLS.  THESE TOOLS 
	MIGHT CHANGE RECORD NUMBERS, GEOMETRY AND/OR FEATURES ON YOUR DATA.  WE ARE RUNNING 
	THIS DUE TO THE LARGE VOLUME OF NON-VALID GEOMETRIES SUBMITTED IN PAST SUBMISSION.  
	IT IS A BEST PRACTICE TO RUN THESE TOOLS INDIVIDUALLY ON SAMPLE DATA PRIOR TO 
	RUNNING THE CHECKSUBMISSION TOOL SO YOU ARE FAMILIAR WITH GEOMETRY ISSUES CONTAINED 
	IN YOUR SUBMISSION.

- THESe TOOL GENERALLY REQUIRE AN ARCINFO LICENSE TO RUN.  

- THIS TOOL WAS CREATED AND TESTED IN ARCGIS 10.0

